Repository SysRay/psOff_public, pull requests merged in 2024-04, with the labels that each got.

#103 Discord release notifier
  .github/workflows/build.yml
  .github/workflows/release_notify.yml
  misc/discordNotify/.gitignore
  misc/discordNotify/main.js
  misc/discordNotify/package.json
  misc/testRunner/main.js
  misc/testRunner/package.json
  misc/testRunner/summary/.gitignore
  misc/testRunner/summary/.gitkeep
  modules/libSceAudioOut/CMakeLists.txt
  modules/libSceAudioOut/codes.h
  modules/libSceAudioOut/entry.cpp
  modules/libSceCommonDialog/errorcodes.h
  modules/libSceLibcInternal/CMakeLists.txt
  modules/libSceLibcInternal/entry.cpp
  modules/libSceNgs2/codes.h
  modules/libSceNgs2/entry.cpp
  modules/libSceNgs2/types.h
  modules/libSceNpParty/entry.cpp
Labels: general

#106 Fix vsync description + ngs2 things
  core/fileManager/types/type_out.cpp
  core/initParams/initParams.cpp
  modules/libSceIme/types.h
  modules/libSceJson2/types.h
  modules/libSceNgs2/codes.h
  modules/libSceNgs2/entry.cpp
  modules/libSceNgs2/types.h
Labels: bugfix

#105 Multiple Symbols
  modules/libSceGraphicsDriver/entry.cpp
  modules/libSceLibcInternal/entry.cpp
  modules/libSceNetCtlForNpToolkit/entry.cpp
  modules/libSceNpMatching2/CMakeLists.txt
  modules/libSceNpMatching2/codes.h
  modules/libSceNpMatching2/entry.cpp
  modules/libSceNpMatching2/types.h
  modules/libScePad/entry.cpp
  modules/libScePad/types.h
  modules/libScePosix/entry.cpp
  modules/libScePosix/types.h
Labels: implementation, stub

#110 libSceVoice Symbols
  modules/libSceVoice/entry.cpp
  modules/libSceVoice/types.h
Labels: stub

#112 Multiple Symbols (Part 2)
  modules/libSceAjm/entry.cpp
  modules/libSceCamera/entry.cpp
  modules/libSceCamera/types.h
  modules/libSceDepth/CMakeLists.txt
  modules/libSceDepth/codes.h
  modules/libSceDepth/entry.cpp
  modules/libSceDepth/types.h
  modules/libSceHmd/CMakeLists.txt
  modules/libSceHmd/codes.h
  modules/libSceHmd/entry.cpp
  modules/libSceHmd/types.h
  modules/libSceMoveTracker/CMakeLists.txt
  modules/libSceMoveTracker/codes.h
  modules/libSceMoveTracker/entry.cpp
  modules/libSceMoveTracker/types.h
  modules/libScePad/entry.cpp
Labels: stub

#55 Wiki thing
  .github/workflows/upwiki.yml
  docs/wiki/Building-psOff-VSCode.md
  docs/wiki/Building-psOff-from-scratch.md
  docs/wiki/Config-files.md
  docs/wiki/Home.md
Labels: general

#104 libSceHttp early implementation
  modules/libSceHttp/CMakeLists.txt
  modules/libSceHttp/codes.h
  modules/libSceHttp/entry.cpp
  modules/libSceNet/types.h
Labels: implementation

#113 Fix wiki action
  .github/workflows/upwiki.yml
  docs/README.md
  docs/wiki/images/vsbuild/cmake_build.png
  docs/wiki/images/vsbuild/cmake_configure.png
  docs/wiki/images/vsbuild/cmake_pins.png
  docs/wiki/images/vsbuild/debug_warning.png
  docs/wiki/images/vsbuild/default_compiler.png
  docs/wiki/images/vsbuild/default_compiler_popup.png
  docs/wiki/images/vsbuild/default_compiler_sure.png
  docs/wiki/images/vsbuild/optimizations.png
  docs/wiki/images/vsbuild/recomends_btn.png
  docs/wiki/images/vsbuild/recomends_help.png
  docs/wiki/images/vsbuild/recomends_install.png
  docs/wiki/markdown/Building-psOff-VSCode.md
  docs/wiki/markdown/Building-psOff-from-scratch.md
  docs/wiki/markdown/Config-files.md
  docs/wiki/markdown/Home.md
Labels: general

#114 Some libc missing syms
  .clang-format
  core/kernel/semaphore_fifo.cpp
  core/videoout/videoout.cpp
  modules/libSceAvPlayer/avplayer.cpp
  modules/libSceHttp/entry.cpp
  modules/libSceLibcInternal/entry.cpp
Labels: implementation

#111 Moving net code to core
  .clang-format-ignore
  core/CMakeLists.txt
  core/kernel/pthread.cpp
  core/kernel/semaphore_fifo.cpp
  core/networking/CMakeLists.txt
  core/networking/networking.cpp
  core/networking/networking.h
  core/networking/states/offline.cpp
  core/networking/states/offline.h
  core/networking/states/online.h
  core/networking/states/online/epoll.cpp
  core/networking/states/online/http.cpp
  core/networking/states/online/netctl.cpp
  core/networking/states/online/resolver.cpp
  core/networking/states/online/socket.cpp
  core/networking/wepoll.c
  core/networking/wepoll.h
  modules/libSceHttp/CMakeLists.txt
  modules/libSceHttp/entry.cpp
  modules/libSceHttp/httpsTypes.h
  modules/libSceHttp/types.h
  modules/libSceNet/CMakeLists.txt
  modules/libSceNet/README.md
  modules/libSceNet/codes.h
  modules/libSceNet/entry.cpp
  modules/libSceNet/epoll.cpp
  modules/libSceNet/resolver.cpp
  modules/libSceNet/socket.cpp
  modules/libSceNet/types.h
  modules/libSceNetCtl/CMakeLists.txt
  modules/libSceNetCtl/codes.h
  modules/libSceNetCtl/entry.cpp
  modules/libSceNgs2/entry.cpp
  modules/libkernel/dmem.cpp
  tools/config_emu/config_emu.cpp
  tools/gamereport/entry.cpp
Labels: implementation, stub

#115 Multiple gamepads support
  modules/libScePad/interfaces/ikbd.cpp
  modules/libScePad/interfaces/isdl.cpp
  modules/libScePad/interfaces/ixip.cpp
  modules/libSceUserService/entry.cpp
  tools/config_emu/config_emu.cpp
Labels: enhancement

#116 Some config range checks and wiki update
  core/videoout/videoout.cpp
  docs/wiki/markdown/Config-files.md
  misc/discordNotify/main.js
  modules/libSceUserService/entry.cpp
  tools/config_emu/config_emu.cpp
  tools/config_emu/config_emu.h
Labels: general, bugfix

#117 Multiple stubs and implementations
  misc/testRunner/main.js
  modules/libSceGameLiveStreaming/entry.cpp
  modules/libSceGameLiveStreaming/types.h
  modules/libSceJson2/entry.cpp
  modules/libSceLibcInternal/entry.cpp
  modules/libSceSaveData/entry.cpp
  modules/libSceSaveData/types.h
  modules/libSceSharePlay/entry.cpp
  modules/libSceSharePlay/types.h
Labels: implementation, stub

#118 Toggle fullscreen keybind
  core/videoout/videoout.cpp
Labels: enhancement

#119 Minor libSceUlt research
  .vscode/settings.json
  modules/libSceUlt/CMakeLists.txt
  modules/libSceUlt/codes.h
  modules/libSceUlt/entry.cpp
  modules/libSceUlt/types.h
  modules/libkernel/entry.cpp
Labels: implementation

#120 More stubs, libc implementations and scePadOpen fix
  modules/libSceCamera/entry.cpp
  modules/libSceLibcInternal/entry.cpp
  modules/libScePad/entry.cpp
  modules/libScePosix/entry.cpp
  modules/libSceUserService/entry.cpp
Labels: bugfix, implementation, stub

#123 Add json validation schemas to config files
  CMakeLists.txt
  docs/json/audio.json
  docs/json/controls.json
  docs/json/general.json
  docs/json/graphics.json
  docs/json/logging.json
  tools/config_emu/config_emu.cpp
Labels: enhancement

#125 Error codes cleanup + more scePad fixes
  core/networking/networking.h
  core/networking/states/offline.cpp
  core/networking/states/offline.h
  core/networking/states/online.h
  core/networking/states/online/netctl.cpp
  core/videoout/videoout.cpp
  modules/libSceAudioOut/codes.h
  modules/libSceAudioOut/entry.cpp
  modules/libSceAvPlayer/codes.h
  modules/libSceAvPlayer/entry.cpp
  modules/libSceAvPlayer/entryEx.cpp
  modules/libSceCommonDialog/codes.h
  modules/libSceCommonDialog/entry.cpp
  modules/libSceCommonDialog/errorcodes.h
  modules/libSceDiscMap/codes.h
  modules/libSceDiscMap/entry.cpp
  modules/libSceGraphicsDriver/codes.h
  modules/libSceGraphicsDriver/entry.cpp
  modules/libSceJson2/codes.h
  modules/libSceNetCtl/entry.cpp
  modules/libSceNgs2/codes.h
  modules/libSceNgs2/entry.cpp
  modules/libSceNpGameIntent/codes.h
  modules/libSceNpGameIntent/entry.cpp
  modules/libSceNpToolkit2/codes.h
  modules/libSceNpToolkit2/entry.cpp
  modules/libScePad/codes.h
  modules/libScePad/entry.cpp
  modules/libScePad/interfaces/ikbd.cpp
  modules/libScePad/interfaces/isdl.cpp
  modules/libScePad/interfaces/ixip.cpp
  modules/libScePngDec/codes.h
  modules/libScePngDec/entry.cpp
  modules/libSceRtc/codes.h
  modules/libSceSaveData/codes.h
  modules/libSceSaveData/entry.cpp
  modules/libSceSystemGesture/codes.h
  modules/libSceSystemGesture/entry.cpp
  modules/libSceUserService/codes.h
  modules/libSceUserService/entry.cpp
  modules/libSceVideoOut/codes.h
  modules/libSceVideoOut/entry.cpp
Labels: general, bugfix

#126 Update wiki info and json schemas
  docs/json/audio.json
  docs/json/controls.json
  docs/json/general.json
  docs/json/graphics.json
  docs/json/logging.json
  docs/wiki/markdown/Building-psOff-from-scratch.md
  docs/wiki/markdown/Config-files.md
Labels: enhancement

#131 libScePad and libScePthread fixes + some stubs
  core/kernel/pthread.cpp
  modules/libSceAudioOut/entry.cpp
  modules/libSceHttp/entry.cpp
  modules/libSceJson2/entry.cpp
  modules/libSceJson2/types.h
  modules/libSceNpAuth/entry.cpp
  modules/libScePad/entry.cpp
  modules/libkernel_cpumode_platform/CMakeLists.txt
  modules/libkernel_cpumode_platform/codes.h
  modules/libkernel_cpumode_platform/entry.cpp
  modules/libkernel_cpumode_platform/types.h
Labels: bugfix

#132 Get rid of pad's backend aliases
  .vscode/launch.json
  core/kernel/filesystem.cpp
  docs/json/controls.json
  docs/wiki/markdown/Config-files.md
  modules/libScePad/cconfig.cpp
  modules/libScePosix/entry.cpp
  modules/libSceUserService/entry.cpp
  tools/config_emu/config_emu.cpp
  tools/gamereport/CMakeLists.txt
  tools/gamereport/entry.cpp
Labels: general
